version: 1

models:
  - name: stg__dvd_rental_category
    description: '{{ doc("stg__dvd_rental_category") }}'
    columns:
      - name: category_id
        description: "Unique Identifier of a category"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name identifier of a category"
        tests:
          - not_null
      - name: last_update
        description: "Timestamp of the last update made to a row" 
        tests:
          - not_null

  - name: stg__dvd_rental_film_category
    description: '{{ doc("stg__dvd_rental_film_category") }}'
    columns:
      - name: film_id
        description: "Unique Identifier of a film category"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_film')
              field: film_id
      - name: category_id
        description: "Name identifier of a film category"
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_category')
              field: category_id
      - name: last_update
        description: "Timestamp of the last update made to a row" 
        tests:
          - not_null

  - name: stg__dvd_rental_film
    description: '{{ doc("stg__dvd_rental_film") }}'
    columns:
      - name: film_id
        description: "Unique Identifier of the film"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name: release_year
        description: "Year of the film was released"
        tests:
          - not_null
      - name: rental_duration
        description: "Rental duration of the film"
        tests:
          - not_null
      - name: rental_rate
        description: "Rate given to the rental"
        tests:
          - not_null
      - name: replacement_cost
        description: "Cost of replacing the film"
        tests:
          - not_null
      - name: last_update
        description: "Timestamp of the last update made to a row"
        tests:
          - not_null

  - name: stg__dvd_rental_inventory
    description: '{{ doc("stg__dvd_rental_inventory") }}'
    columns:
      - name: inventory_id
        description: "Unique Identifier of the inventory"
        tests:
          - unique
          - not_null
      - name: film_id
        description: "ID of a film in the inventory"
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_film')
              field: film_id
      - name: store_id
        description: "ID of a store that has a matching film in inventory"
        tests:
          - not_null
      - name: last_update
        description: "Timestamp of the last update made to a row" 
        tests:
          - not_null

  - name: stg__dvd_rental_payment
    description: '{{ doc("stg__dvd_rental_payment") }}'
    columns:
      - name: payment_id
        description: "Unique Identifier of the payment"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID of the customer that made the payment"
        tests:
          - not_null
      - name: staff_id
        description: "ID of the staff person that received the payment"
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_staff')
              field: staff_id
      - name: rental_id
        description: "ID of the rental to which the payment corresponds"
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_rental')
              field: rental_id
      - name: amount
        description: "Numeric value of the amount payed, with a total 5 digits, with 2 digits after the decimal point"
        tests:
          - not_null
      - name: payment_date
        description: "Timestamp of the date in which the payment was executed"
        tests:
          - not_null

  - name: stg__dvd_rental_rental
    description: '{{ doc("stg__dvd_rental_rental") }}'
    columns:
      - name: rental_id
        description: "Unique Identifier of the rental"
        tests:
          - unique
          - not_null
      - name: rental_date
        description: "Timestamp of the date corresponding to the start of the rental"
        tests:
          - not_null
      - name: inventory_id
        description: "ID of the inventory to rent"
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_inventory')
              field: inventory_id
      - name: customer_id
        description: "ID of the customer that rented the requested inventory" 
        tests:
          - not_null
      - name: return_date
        description: "Timestamp of the date corresponding to the end of the rental" 
      - name: staff_id
        description: "ID of the staff that made the rental" 
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_staff')
              field: staff_id
      - name: last_update
        description: "Timestamp of the last update made to a row" 
        tests:
          - not_null

  - name: stg__dvd_rental_staff
    description: '{{ doc("stg__dvd_rental_staff") }}'
    columns:
      - name: staff_id
        description: "Unique Identifier of the staff"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the staff"
        tests:
          - not_null
      - name: last_name
        description: "Last name of the staff"
        tests:
          - not_null
      - name: address_id
        description: "ID of the staff address"
        tests:
          - not_null
      - name: store_id
        description: "ID of the store where the staff works"
        tests:
          - unique
          - not_null
      - name: active
        description: "Identifies if the staff is active or inactive"
        tests:
          - not_null
          - accepted_values:
              values: ['true', 'false'] 
      - name: username
        description: "Username of the corresponding staff"
        tests:
          - unique
          - not_null
      - name: last_update
        description: "Timestamp of the last update made to a row"
        tests:
          - not_null
  

  - name: stg__dvd_rental_customer
    description: '{{ doc("stg__dvd_rental_customer") }}'
    columns:
      - name: customer_id
        description: "Unique identifier of the customer"
        tests:
          - unique
          - not_null

      - name: store_id
        description: "Identifier of the store the customer is associated with"
        tests:
          - not_null
          - relationships:
              to: ref('stg__dvd_rental_store')
              field: store_id

      - name: is_active
        description: "Indicates whether the customer is currently active"
        tests:
          - not_null
          - accepted_values:
              values: ['true', 'false']

      - name: created_at
        description: "Timestamp when the customer was created"
        tests:
          - not_null

      - name: updated_at
        description: "Timestamp of the last update made to a row"
        tests:
          - not_null
