version: 1

models:
  - name: fct_rental_performance_by_store
    description: '{{ doc("fct_rental_performance_by_store") }}'
    columns:
      - name: store_id
        description: "Store identifier"
        tests:
          - not_null
      - name: total_rentals
        description: "Sum of all the rentals by store each month"
        tests:
          - not_null
      - name: avg_rental_duration
        description: "Average duration rentals by store each month"
        tests:
          - not_null
      - name: month
        description: "Year and Month identifier"
        tests:
          - not_null

  - name: fct_revenue_performance_by_store
    description: '{{ doc("fct_revenue_performance_by_store") }}'
    columns:
      - name: store_id
        description: "Identifier of the store"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue earned by a store in the corresponding month"
        tests:
          - not_null
      - name: month
        description: "Year and Month identifier"
        tests:
          - not_null

  - name: fct_most_rented_category_by_period_by_store
    description: '{{ doc("fct_most_rented_category_by_period_by_store") }}'
    columns:
      - name: store_id
        description: "Store identifier"
        tests:
          - not_null
      - name: month
        description: "Year and month of the rental activity"
        tests:
          - not_null
      - name: category_name
        description:  "Name of the film category with the most rentals in the given month and store"
        tests:
          - not_null
      - name: rental_count
        description: "Total number of rentals for the most rented category in the given month and store"
        tests:
          - not_null