version: 1

models:
  - name: int__dvd_rental_payment_store
    description: '{{ doc("int__dvd_rental_payment_store") }}'
    columns:
      - name: payment_id
        description: "Unique identifier of the payment"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Identifier for the customer that made the payment"
        tests:
          - not_null
      - name: staff_id
        description: "Identifier of the staff id that received the payment"
        tests:
          - not_null
      - name: amount
        description: "Numeric amount of the value payed in each payment"
        tests:
          - not_null
      - name: payment_date
        description: "Timestamp of the date in which the payment was made"
        tests:
          - not_null
      - name: store_id
        description: "Identifier of the store where the payment was made"
        tests:
          - not_null

  - name: int__dvd_rental_rentals_by_category
    description: '{{ doc("int__dvd_rental_rentals_by_category") }}'
    columns:
      - name: store_id
        description: "Store where the rental occurred"
        tests:
          - not_null
      - name: category_name
        description: "Category of the rented film"
        tests:
          - not_null
      - name: rental_count
        description: "Count of the rentals made by store and category name"
        tests:
          - not_null

  - name: int__dvd_rental_rentals_per_film
    description: '{{ doc("int__dvd_rental_rentals_per_film") }}'
    columns:
      - name: film_id
        description: "Unique identifier of the film"
        tests:
          - not_null
      - name: title
        description: "Name of the film title"
        tests:
          - not_null
      - name: store_id
        description: "Store where the film is rented at"
        tests:
          - not_null
      - name: rental_count
        description: "Count of the rentals made of a film, by store and title"
        tests:
          - not_null

  - name: int__dvd_rental_customer_revenue
    description: '{{ doc("int__dvd_rental_customer_revenue") }}'
    columns:
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: store_id
        description: "Store identifier"
        tests:
          - not_null
      - name: month
        description: "Month of the last payment made by the customer"
        tests:
          - not_null
      - name: total_revenue
        description: "Sum of payments made by the customer"
        tests:
          - not_null
      - name: num_payments
        description: "Quantity of payments made by the customer"
        tests:
          - not_null
      - name: total_rentals
        description: "Quantity of rentals made by the customer"
        tests:
          - not_null

  - name: int__dvd_rental_store_performance
    description: '{{ doc("int__dvd_rental_store_performance") }}'
    columns:
      - name: store_id
        description: "Store identifier"
      - name: month
        description: "Month identifier"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the store"
      - name: total_rentals
        description: "Total number of rentals in the store"
      - name: avg_rental_duration
        description: "Average duration of rentals at the store"