version: 1

models:
  - name: int__dvd_rental_payment_store
    description: "Intermediate model that aggregates total payment amount per store and month"
    columns:
      - name: store_id
        description: "Unique identifier of the store"
        tests:
          - not_null
      - name: month
        description: "Month the payment was made"
        tests:
          - not_null
      - name: total_payment
        description: "Total amount of payments made at the store during the month"
        tests:
          - not_null

  - name: int__dvd_rental_rentals_by_category
    description: "Aggregates number of rentals per category, store, and month"
    columns:
      - name: store_id
        description: "Store where the rental occurred"
        tests:
          - not_null
      - name: month
        description: "Month of the rental"
        tests:
          - not_null
      - name: category_name
        description: "Category of the rented film"
        tests:
          - not_null
      - name: rental_count
        description: "Total number of rentals for the category in that store/month"
        tests:
          - not_null

  - name: int__dvd_rental_rentals_per_film
    description: "Counts rentals per film"
    columns:
      - name: film_id
        description: "Unique identifier of the film"
        tests:
          - not_null
      - name: rental_count
        description: "Total number of times the film was rented"
        tests:
          - not_null

  - name: int__dvd_rental_customer_revenue
    description: "Aggregates total revenue per customer"
    columns:
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: total_revenue
        description: "Sum of payments made by the customer"
        tests:
          - not_null

  - name: int__dvd_rental_store_performance
    description: "Combined store-level performance metrics used to build the store performance index"
    columns:
      - name: store_id
        description: "Store identifier"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the store"
        tests:
          - not_null
      - name: total_rentals
        description: "Total number of rentals in the store"
        tests:
          - not_null
      - name: avg_rental_duration
        description: "Average duration of rentals at the store"
        tests:
          - not_null
